version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    ports:
      - "5001:5000"
    environment:
      - LOG_LEVEL=INFO
      - TRY_URL=http://example.org/
      - PROXY_DB_PATH=tmp/proxy.db
      - GEOIP_DB_PATH=tmp/geoip.db
      - GEOIP_DB_DOWNLOAD_URL=https://download.db-ip.com/free/dbip-city-lite-2020-12.csv.gz
      - NODES_INIT_PATH=nodes-init.txt
    volumes:
      - ./tmp:/code/tmp

  tasks:
    build:
      context: .
      dockerfile: docker/tasks/Dockerfile
    restart: always
    environment:
      - LOG_LEVEL=INFO
      - TRY_URL=http://example.org/
      - PROXY_DB_PATH=tmp/proxy.db
      - GEOIP_DB_PATH=tmp/geoip.db
      - PROXY_SEARCH_THREADS=100
      - NET_BLACKLIST=
      - INSTANCE_URL=
    volumes:
      - ./tmp:/code/tmp
    depends_on:
      - api
