version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    ports:
      - "5001:5000"
    environment:
      - LOG_LEVEL=INFO
      - TRY_URL=http://example.org/
      - PROXY_DB_PATH=tmp/proxy.db
      - GEOIP_DB_PATH=tmp/geoip.db
    volumes:
      - ./tmp:/code/tmp

  tasks:
    build:
      context: .
      dockerfile: docker/tasks/Dockerfile
    restart: always
    environment:
      - LOG_LEVEL=INFO
      - TRY_URL=http://example.org/
      - PROXY_DB_PATH=tmp/proxy.db
      - GEOIP_DB_PATH=tmp/geoip.db
      - PROXY_SEARCH_THREADS=100
    volumes:
      - ./tmp:/code/tmp
